import { NextRequest, NextResponse } from 'next/server';

const RPC_URLS = [
  'https://rpc.starknet-testnet.lava.build',
  'https://free-rpc.nethermind.io/sepolia-juno/',
];

async function fetchTxStatus(txHash: string) {
  for (const rpcUrl of RPC_URLS) {
    try {
      // Get transaction receipt — contains execution status
      const receiptRes = await fetch(rpcUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          jsonrpc: '2.0',
          method: 'starknet_getTransactionReceipt',
          params: [txHash],
          id: 1,
        }),
      });
      const receiptData = await receiptRes.json();

      // Get transaction status — contains finality_status (L1 proof)
      const statusRes = await fetch(rpcUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          jsonrpc: '2.0',
          method: 'starknet_getTransactionStatus',
          params: [txHash],
          id: 2,
        }),
      });
      const statusData = await statusRes.json();

      if (receiptData?.result || statusData?.result) {
        const receipt = receiptData?.result || {};
        const status = statusData?.result || {};

        const executionStatus = receipt.execution_status || status.execution_status || 'UNKNOWN';
        const finalityStatus = receipt.finality_status || status.finality_status || 'RECEIVED';
        const blockNumber = receipt.block_number || null;

        // Map to ZK proof stages
        let zkStage = 'PENDING';
        let zkLabel = 'Proof Pending';
        let zkColor = '#f59e0b';
        let zkDescription = 'Transaction submitted, awaiting STARK proof generation.';

        if (finalityStatus === 'ACCEPTED_ON_L1') {
          zkStage = 'PROVED_L1';
          zkLabel = 'STARK Proof Verified on L1';
          zkColor = '#4ade80';
          zkDescription = 'STARK proof submitted and verified on Ethereum L1. Mathematically guaranteed.';
        } else if (finalityStatus === 'ACCEPTED_ON_L2') {
          zkStage = 'PROVED_L2';
          zkLabel = 'STARK Proof on L2';
          zkColor = '#60a5fa';
          zkDescription = 'Transaction proven by Starknet STARK prover. Awaiting L1 settlement.';
        } else if (executionStatus === 'SUCCEEDED') {
          zkStage = 'EXECUTED';
          zkLabel = 'Executed — Proof Generating';
          zkColor = '#a78bfa';
          zkDescription = 'Transaction executed successfully. STARK proof being generated by Starknet provers.';
        }

        return {
          txHash,
          zkStage,
          zkLabel,
          zkColor,
          zkDescription,
          executionStatus,
          finalityStatus,
          blockNumber,
          rpc: rpcUrl,
        };
      }
    } catch (err) {
      console.warn('RPC failed for proof:', rpcUrl, err);
    }
  }
  return {
    txHash,
    zkStage: 'UNKNOWN',
    zkLabel: 'Checking Proof...',
    zkColor: '#6b7280',
    zkDescription: 'Fetching proof status from Starknet network.',
    executionStatus: 'UNKNOWN',
    finalityStatus: 'UNKNOWN',
    blockNumber: null,
  };
}

export async function GET(req: NextRequest) {
  const txHash = req.nextUrl.searchParams.get('tx');
  if (!txHash) return NextResponse.json({ error: 'No tx hash' }, { status: 400 });

  const result = await fetchTxStatus(txHash);
  return NextResponse.json(result);
}